import type { Product } from "@/types";

export const sampleProducts: Product[] = [
  {
    id: "1",
    name: "MAP OF THE SOUL : 7 정규 앨범",
    description: "방탄소년단의 네 번째 정규 앨범. VERSION 01, 02, 03, 04 총 4가지 버전으로 구성되어 있으며, 각 버전별 포토카드와 포토북이 포함되어 있습니다.",
    price: 22000,
    category: "album",
    member: null,
    images: [],
    options: [{ name: "버전", values: ["VERSION 01", "VERSION 02", "VERSION 03", "VERSION 04"] }],
    stock: 150,
    is_new: false,
    is_popular: true,
    created_at: "2024-02-21T00:00:00Z",
  },
  {
    id: "2",
    name: "BE (Deluxe Edition) 정규 앨범",
    description: "방탄소년단이 직접 프로듀싱에 참여한 앨범. 포토카드 8종 중 랜덤 1종 포함.",
    price: 35000,
    category: "album",
    member: null,
    images: [],
    options: [],
    stock: 80,
    is_new: false,
    is_popular: true,
    created_at: "2024-11-20T00:00:00Z",
  },
  {
    id: "3",
    name: "Proof (Standard Edition) 앤솔로지 앨범",
    description: "방탄소년단 데뷔 9주년 기념 앤솔로지 앨범. CD 3장 구성.",
    price: 28000,
    category: "album",
    member: null,
    images: [],
    options: [],
    stock: 120,
    is_new: false,
    is_popular: true,
    created_at: "2024-06-10T00:00:00Z",
  },
  {
    id: "4",
    name: "GOLDEN 정규 앨범 (정국)",
    description: "정국의 첫 솔로 앨범 GOLDEN. SHINE, SOLID, SUBSTANCE 3가지 버전.",
    price: 19800,
    category: "album",
    member: "정국",
    images: [],
    options: [{ name: "버전", values: ["SHINE", "SOLID", "SUBSTANCE"] }],
    stock: 200,
    is_new: true,
    is_popular: true,
    created_at: "2025-11-03T00:00:00Z",
  },
  {
    id: "5",
    name: "D-DAY 앨범 (슈가)",
    description: "Agust D의 세 번째 믹스테이프 앨범. 포토북, 포토카드 포함.",
    price: 21000,
    category: "album",
    member: "슈가",
    images: [],
    options: [{ name: "버전", values: ["VERSION 01", "VERSION 02"] }],
    stock: 90,
    is_new: false,
    is_popular: false,
    created_at: "2024-04-21T00:00:00Z",
  },
  {
    id: "6",
    name: "Right Place, Wrong Person (RM)",
    description: "RM의 두 번째 솔로 앨범. 감성적인 아트워크와 함께한 포토북 포함.",
    price: 20500,
    category: "album",
    member: "RM",
    images: [],
    options: [{ name: "버전", values: ["VERSION 01", "VERSION 02"] }],
    stock: 110,
    is_new: true,
    is_popular: false,
    created_at: "2025-05-24T00:00:00Z",
  },
  {
    id: "7",
    name: "BTS 포토카드 세트 — MAP OF THE SOUL",
    description: "MAP OF THE SOUL : 7 앨범 수록 포토카드 풀세트. 멤버별 2장씩 총 14장 구성.",
    price: 15000,
    category: "photocard",
    member: null,
    images: [],
    options: [],
    stock: 60,
    is_new: false,
    is_popular: true,
    created_at: "2024-03-01T00:00:00Z",
  },
  {
    id: "8",
    name: "뷔 포토카드 랜덤팩 (5장)",
    description: "뷔 단독 포토카드 랜덤팩. 다양한 시즌의 포토카드 5장이 랜덤으로 구성됩니다.",
    price: 8000,
    category: "photocard",
    member: "뷔",
    images: [],
    options: [],
    stock: 200,
    is_new: true,
    is_popular: true,
    created_at: "2025-12-01T00:00:00Z",
  },
  {
    id: "9",
    name: "지민 포토카드 랜덤팩 (5장)",
    description: "지민 단독 포토카드 랜덤팩. FACE, MUSE 앨범 등 다양한 시즌 포토카드 5장.",
    price: 8000,
    category: "photocard",
    member: "지민",
    images: [],
    options: [],
    stock: 180,
    is_new: true,
    is_popular: true,
    created_at: "2025-12-01T00:00:00Z",
  },
  {
    id: "10",
    name: "진 포토카드 컬렉션 (10장)",
    description: "진 솔로 활동 기념 포토카드 스페셜 컬렉션. 한정판 10장 세트.",
    price: 16000,
    category: "photocard",
    member: "진",
    images: [],
    options: [],
    stock: 50,
    is_new: true,
    is_popular: false,
    created_at: "2025-12-15T00:00:00Z",
  },
  {
    id: "11",
    name: "제이홉 포토카드 세트 (8장)",
    description: "Jack In The Box / HOPE ON THE STREET 시리즈 포토카드 8장 세트.",
    price: 12000,
    category: "photocard",
    member: "제이홉",
    images: [],
    options: [],
    stock: 70,
    is_new: false,
    is_popular: false,
    created_at: "2024-07-15T00:00:00Z",
  },
  {
    id: "12",
    name: "BTS 2025 시즌그리팅",
    description: "2025 시즌그리팅 세트. 다이어리, 캘린더, 포토카드, 포토북 구성.",
    price: 38000,
    category: "season_md",
    member: null,
    images: [],
    options: [],
    stock: 40,
    is_new: true,
    is_popular: true,
    created_at: "2025-12-20T00:00:00Z",
  },
  {
    id: "13",
    name: "BTS 공식 키링 세트 (7종)",
    description: "멤버별 캐릭터 키링 7종 세트. TinyTAN 디자인.",
    price: 25000,
    category: "season_md",
    member: null,
    images: [],
    options: [],
    stock: 100,
    is_new: false,
    is_popular: true,
    created_at: "2024-09-01T00:00:00Z",
  },
  {
    id: "14",
    name: "BTS 공식 포스터 세트 (4장)",
    description: "고화질 공식 포스터 세트. A2 사이즈, 양면 인쇄.",
    price: 18000,
    category: "season_md",
    member: null,
    images: [],
    options: [],
    stock: 150,
    is_new: false,
    is_popular: false,
    created_at: "2024-05-01T00:00:00Z",
  },
  {
    id: "15",
    name: "MUSE 미니앨범 (지민)",
    description: "지민의 두 번째 솔로 앨범 MUSE. BLOOMING, SERENADE 2가지 버전.",
    price: 18500,
    category: "album",
    member: "지민",
    images: [],
    options: [{ name: "버전", values: ["BLOOMING", "SERENADE"] }],
    stock: 160,
    is_new: true,
    is_popular: true,
    created_at: "2025-07-19T00:00:00Z",
  },
  {
    id: "16",
    name: "TYPE 1 미니앨범 (뷔)",
    description: "뷔의 첫 솔로 앨범. Layover의 감성을 담은 아트워크 포토북 포함.",
    price: 19000,
    category: "album",
    member: "뷔",
    images: [],
    options: [{ name: "버전", values: ["Phantom", "Noir"] }],
    stock: 140,
    is_new: true,
    is_popular: true,
    created_at: "2025-09-10T00:00:00Z",
  },
];
